[tox]
args_are_paths = false
envlist =
    py{310,311,312,313}-django52
    py{312,313,314}-django60
    py{312,313,314}-djangomain

[testenv]
usedevelop = true
allowlist_externals = make
commands = make test
pip_pre = true
deps =
    django52: Django>=5.2,<6.0
    django60: Django>=6.0,<6.1
    djangomain: https://github.com/django/django/archive/main.tar.gz
    -r{toxinidir}/tests/requirements.txt
ignore_outcome =
    djangomain: True
ignore_errors =
    djangomain: True

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
